(function(){var startingTime=new Date().getTime();var script=document.createElement("SCRIPT");script.src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js';script.type='text/javascript';document.getElementsByTagName("head")[0].appendChild(script);var atree=document.createElement("SCRIPT");atree.src='steffscript2.js';atree.type='text/javascript';document.getElementsByTagName("head")[0].appendChild(atree);var ulItems=document.querySelectorAll(".menu a");var blink=document.createElement("blink");blink.textContent="SURPRISE!!";document.querySelectorAll(".column")[0].appendChild(blink);var treeCanvas=document.createElement("canvas");treeCanvas.id='scene';treeCanvas.width=500;treeCanvas.height=500;treeCanvas.style='background:black; display: block; margin: 0 auto; width: 300px; height: 300px;';document.querySelectorAll(".column")[0].appendChild(treeCanvas);var audio=document.createElement("audio");audio.src='https://cdn.pixabay.com/download/audio/2022/05/17/audio_581ce59413.mp3?filename=metal-dark-matter-111451.mp3';document.getElementsByTagName("head")[0].appendChild(audio);var hat=document.createElement("img");hat.setAttribute("src","https://i.postimg.cc/sz8RFjmv/pngwing-com.png?dl=1");hat.setAttribute("height","50");hat.setAttribute("width","75");hat.setAttribute("alt","Hat");hat.setAttribute("style","position: absolute;top: 65px;left: 70px;}");document.querySelectorAll(".column")[0].appendChild(hat);var checkReady=function(callback){if(window.jQuery){callback(jQuery);}
else{window.setTimeout(function(){checkReady(callback);},20);}};window.setTimeout(()=>{const audio=document.querySelector("audio");audio.volume=0.2;audio.loop=true
    audio.play();setInterval(function(){blink.style.color=getRandomColor();for(var i=0;i<ulItems.length;i++){ulItems[i].style.color=getRandomColor();}},1000);runTree();},5000)
    const addCSS=css=>document.head.appendChild(document.createElement("style")).innerHTML=css;checkReady(function($){$(function(){var endingTime=new Date().getTime();var tookTime=endingTime-startingTime;});if($.browser.msie&&parseInt($.browser.version)<8)return;var fps=30;var addNewFlakesEveryNFrames=10;var newFlakesToAdd=3;var speedControl=0.7;var flakes=[];var additionCounter=0;function createFlake(curX,curY){var maxSpeedOffset=2;var maxWiggleOffset=10;var minSize=5;var maxSize=15;var minWiggle=10;var maxWiggle=40;var sizePercent=Math.random();var size=Math.floor(sizePercent*(maxSize-minSize)+minSize);var opacity=0.3+Math.random()*0.7;if($.browser.msie&&parseInt($.browser.version)<10)
        opacity=undefined;var color='#9CF';var speedOffset=Math.floor(Math.random()*maxSpeedOffset);var wiggle=minWiggle+(maxWiggleOffset*Math.random())+(maxWiggle-minWiggle)*sizePercent;var flake=$('<div>').text(' ').css({position:'fixed',left:curX,top:curY,zIndex:1000000,width:size,height:size,opacity:opacity,borderRadius:size/2,'-moz-border-radius':size/2,'-webkit-border-radius':size/2,backgroundColor:color}).appendTo('body');var flakeObj={size:size,sizePercent:sizePercent,homeX:curX,curX:curX,curY:curY,flake:flake,uniqueSpeedOffset:speedOffset,wiggle:wiggle,wiggleCounter:Math.floor(100*Math.random())};flakes.push(flakeObj);return flakeObj;}
        var sinTable=[];for(var i=0;i<100;i++){var sin=Math.sin((i/100)*Math.PI*2);sinTable.push(sin);}
        var mouseX=-200;var mouseY=-200;var $w=$(window);$(document).mousemove(function(e){mouseX=e.pageX-$w.scrollLeft();mouseY=e.pageY-$w.scrollTop();});function onEnterFrame(){var winH=$w.height();for(var i=flakes.length-1;i>-1;i--){var flakeObj=flakes[i];var flake=flakeObj.flake;var speed=2+(1-flakeObj.sizePercent)*5+flakeObj.uniqueSpeedOffset;speed*=speedControl;var curY=flakeObj.curY;var newY=curY+speed;var wiggleCounter=flakeObj.wiggleCounter=(++flakeObj.wiggleCounter%100);var sin=sinTable[wiggleCounter];var wiggle=flakeObj.wiggle*sin;var newX=flakeObj.homeX+wiggle;var mouseXDist=Math.abs(mouseX-newX);var mouseYDist=Math.abs(mouseY-newY);var influenceArea=150;if(mouseXDist<influenceArea&&mouseYDist<influenceArea){var maxForce=10;var dist=Math.sqrt(mouseXDist*mouseXDist+mouseYDist*mouseYDist);if(dist<influenceArea){var influence=maxForce*(1-(dist/influenceArea));if(mouseY>newY){newY-=influence;if(mouseX<newX)flakeObj.homeX+=influence;else flakeObj.homeX-=influence;}
        else newY+=influence;}}
            flakeObj.curY=newY;flakeObj.curX=newX;flake.css({top:newY,left:newX});if(newY>winH+100){flake.remove();flakeObj.flake=null;flakes.splice(i,1);}}
            if(++additionCounter%addNewFlakesEveryNFrames==0){additionCounter=0;var minX=-100;var maxX=$(window).width()+100;var homeY=-100;for(var i=0;i<newFlakesToAdd;i++){var curX=minX+Math.floor(Math.random()*(maxX-minX));var curY=homeY+Math.floor(100*Math.random());createFlake(curX,curY);}}}
        setInterval(onEnterFrame,1000/fps);});addCSS("body{ background:black; }");function getRandomColor(){var letters='0123456789ABCDEF'.split('');var color='#';for(var i=0;i<6;i++){color+=letters[Math.round(Math.random()*15)];}
        return color;}})();